// Generated by gencpp from file robot_controller/DetectObjects.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROLLER_MESSAGE_DETECTOBJECTS_H
#define ROBOT_CONTROLLER_MESSAGE_DETECTOBJECTS_H

#include <ros/service_traits.h>


#include <robot_controller/DetectObjectsRequest.h>
#include <robot_controller/DetectObjectsResponse.h>


namespace robot_controller
{

struct DetectObjects
{

typedef DetectObjectsRequest Request;
typedef DetectObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectObjects
} // namespace robot_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_controller::DetectObjects > {
  static const char* value()
  {
    return "66b6b06f35191dce919e07c706baac8b";
  }

  static const char* value(const ::robot_controller::DetectObjects&) { return value(); }
};

template<>
struct DataType< ::robot_controller::DetectObjects > {
  static const char* value()
  {
    return "robot_controller/DetectObjects";
  }

  static const char* value(const ::robot_controller::DetectObjects&) { return value(); }
};


// service_traits::MD5Sum< ::robot_controller::DetectObjectsRequest> should match
// service_traits::MD5Sum< ::robot_controller::DetectObjects >
template<>
struct MD5Sum< ::robot_controller::DetectObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_controller::DetectObjects >::value();
  }
  static const char* value(const ::robot_controller::DetectObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_controller::DetectObjectsRequest> should match
// service_traits::DataType< ::robot_controller::DetectObjects >
template<>
struct DataType< ::robot_controller::DetectObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::robot_controller::DetectObjects >::value();
  }
  static const char* value(const ::robot_controller::DetectObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_controller::DetectObjectsResponse> should match
// service_traits::MD5Sum< ::robot_controller::DetectObjects >
template<>
struct MD5Sum< ::robot_controller::DetectObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_controller::DetectObjects >::value();
  }
  static const char* value(const ::robot_controller::DetectObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_controller::DetectObjectsResponse> should match
// service_traits::DataType< ::robot_controller::DetectObjects >
template<>
struct DataType< ::robot_controller::DetectObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::robot_controller::DetectObjects >::value();
  }
  static const char* value(const ::robot_controller::DetectObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_CONTROLLER_MESSAGE_DETECTOBJECTS_H
